### ISSUE TITLE
hold-e layer forwardslash key is giving a baskslash.

### ISSUE THREAD

**Issue by a8ksh4** [artseyio/qmk-artsey#1]
Using this hex file:
https://github.com/artseyio/qmk-artsey/releases/download/20220130-1610/artsey-artsey_thepaintbrush-std-left.hex

**Comment by mcrosson** [comment]
This is actually supposed to be a backslash.

For forward slash you need the A + O combo.

**Comment by a8ksh4** [comment]
Sorry, I meant that it's giving a forward slash rather than a backslash. a+o for forward slash works.

**Comment by mcrosson** [comment]
Oh!

I just pushed a fix. A new release should land shortly with the fix in place.

Thank you for the report

**Comment by a8ksh4** [comment]
Confirmed fixed in the new release.  Thx!
